parameters:
    main:
        # Common hyperparameters
        simulator: 'global'
        env: 'warehouse'
        obs_size: 37
        rollout_steps: 8
        num_actions: 4
        name: 'warehouse'
        influence_model: None
        fully_connected: true
        num_fc_layers: 1
        num_fc_units: [512]
        # Convolutional module
        convolutional: false
        # Recurrent module
        recurrent: true
        num_rec_units: 512
        seq_len: 1
        num_workers: 1
        epsilon: 0.1
        beta: 0.01
        render: True
        policy: 'FNNFSPolicy'
        load_policy: False
        framestack: True
        n_stack: 8
        dset: [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36]
        # dset: [49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68]