parameters:
    main:
        # Common hyperparameters
        simulator: 'global'
        env: 'warehouse'
        obs_size: 37
        rollout_steps: 8
        num_actions: 4
        name: 'global_warehouse_recurrent'
        influence_model: None
        fully_connected: true
        num_fc_layers: 1
        num_fc_units: [512]
        # Convolutional module
        convolutional: false
        # Recurrent module
        recurrent: true
        num_rec_units: 512
        seq_len: 1
        num_workers: 8
        epsilon: 0.1
        beta: 0.1
        render: False
        policy: 'FNNPolicy'
        load_policy: False
        framestack: False