parameters:
    main:
        # Common hyperparameters
        simulator: 'local'
        env: 'warehouse'
        obs_size: 37
        rollout_steps: 8
        num_actions: 4
        name: 'warehouse'
        influence_model: 'nn'
        fully_connected: true
        num_fc_layers: 1
        num_fc_units: [512]
        # Convolutional module
        convolutional: false
        # Recurrent module
        recurrent: true
        num_rec_units: 512
        seq_len: 1
        num_workers: 8
        epsilon: 0.1
        beta: 0.01
        render: False
        policy: 'FNNFSPolicy'
        load_policy: False
        framestack: True
        n_stack: 8
        dset: [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36]

    influence:
        # Common hyperparameters
        seq_len: 100
        recurrent: True
        episode_length: 100
        data_path: '../influence/data/warehouse/'
        lr: 1.0e-4
        num_epochs: 500
        batch_size: 32
        hidden_memory_size: 64
        input_size: 37
        output_size: 4
        n_sources: 4
        checkpoint_path: '../influence/models/warehouse/model'
        aug_obs: False
        load_model: False
        curriculum: False
        dataset_size: 5.0e+4