parameters:
    main:
        # Common hyperparameters
        simulator: 'local'
        env: 'warehouse'
        obs_size: 37
        rollout_steps: 8
        num_actions: 4
        name: 'local_warehouse_iam'
        influence_model: 'nn'
        fully_connected: true
        num_fc_layers: 1
        num_fc_units: [512]
        # Convolutional module
        convolutional: false
        # Recurrent module
        recurrent: true
        num_rec_units: 512
        seq_len: 1
        num_workers: 8
        epsilon: 0.1
        beta: 0.1
        render: False
        policy: 'FNNPolicy'
        load_policy: False
        framestack: False


    influence:
        # Common hyperparameters
        seq_len: 100
        episode_length: 100
        data_path: '../influence/data/warehouse/'
        lr: 1.0e-3
        num_epochs: 500
        batch_size: 32
        hidden_memory_size: 64
        input_size: 37
        output_size: 4
        n_sources: 4
        checkpoint_path: '../influence/models/warehouse/model'
        aug_obs: False
        load_model: False
        curriculum: False
        dataset_size: 5.0e+4