parameters:
    main:
        # Common hyperparameters
        env: 'traffic'
        simulator: 'local'
        name: 'local_traffic'
        influence_model: 'uniform'
        obs_size: 40
        num_workers: 8
        fully_connected: true
        num_fc_layers: 1
        num_fc_units: [256, 128]
        # Convolutional module
        convolutional: false
        # Recurrent module
        recurrent: false
        influence: false
        num_workers: 1

    influence:
        # Common hyperparameters
        seq_len: 1
        episode_length: 300
        data_path: '../influence/data/traffic/'
        lr: 1.0e-3
        n_epochs1: 2000
        n_epochs2: 500
        batch_size: 9600
        hidden_memory_size: 8
        input_size: 40
        output_size: 1
        n_sources: 4
        checkpoint_path: '../influence/models/traffic/model'
        aug_obs: False
        load_model: False
        curriculum: False
        dataset_size1: 5.0e+4
        dataset_size2: 1.0e+4
        train_freq: 5.0e+6