parameters:
    main:
        # Common hyperparameters
        env: 'traffic'
        simulator: 'local'
        name: 'uniform_traffic'
        influence_model: 'uniform'
        eval_steps: 5.0e+4
        num_workers: 1

    influence:
        probs: [0.5, 0.5, 0.5, 0.5]
        seq_len: 1
        episode_length: 300