parameters:
    main:
        # Common hyperparameters
        env: 'traffic'
        simulator: 'local'
        name: 'traffic'
        influence_model: 'uniform'
        num_workers: 8
        policy: 'FNNPolicy'
        seq_len: 1
        framestack: false
        load_policy: false

    influence:
        probs: [0.5, 0.5, 0.5, 0.5]
        seq_len: 1
        episode_length: 300